services:
  web:
    build: .
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app

  mongo:
    image: mongo:5.0
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flask_blog

volumes:
  mongodb_data:
